#pragma once
#define ENGINE_WINDOW_W 1920 
#define ENGINE_WINDOW_H 1080

#define VSYNC_ENABLED true
#define MAX_BONE_INFLUENCES 4

//#define ADDITIVE_BLENDING

#define NUMBER_OF_SPOT_LIGHTS_ALLOWED 256
#define NUMBER_OF_LIGHTS_ALLOWED 256
#define MAX_ANIMATION_BONES 128 

//#define DISPLAYGRID
